package edu.hdu.classbox.mapper;

import edu.hdu.classbox.bean.CrsApply;
import edu.hdu.classbox.bean.CrsApplyExample;
import edu.hdu.classbox.bean.CrsApplyKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrsApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    int countByExample(CrsApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(CrsApplyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    int insert(CrsApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    int insertSelective(CrsApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    List<CrsApply> selectByExample(CrsApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    CrsApply selectByPrimaryKey(CrsApplyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CrsApply record, @Param("example") CrsApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CrsApply record, @Param("example") CrsApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CrsApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CrsApply record);
}