package edu.hdu.classbox.bean;

import java.util.Date;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.CrsNo
     *
     * @mbggenerated
     */
    private String crsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.CrsName
     *
     * @mbggenerated
     */
    private String crsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.CreateTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.CrsNo
     *
     * @return the value of course.CrsNo
     *
     * @mbggenerated
     */
    public String getCrsNo() {
        return crsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.CrsNo
     *
     * @param crsNo the value for course.CrsNo
     *
     * @mbggenerated
     */
    public void setCrsNo(String crsNo) {
        this.crsNo = crsNo == null ? null : crsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.CrsName
     *
     * @return the value of course.CrsName
     *
     * @mbggenerated
     */
    public String getCrsName() {
        return crsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.CrsName
     *
     * @param crsName the value for course.CrsName
     *
     * @mbggenerated
     */
    public void setCrsName(String crsName) {
        this.crsName = crsName == null ? null : crsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.CreateTime
     *
     * @return the value of course.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.CreateTime
     *
     * @param createtime the value for course.CreateTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}