package edu.hdu.classbox.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CourseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table course
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public CourseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCrsNoIsNull() {
            addCriterion("CrsNo is null");
            return (Criteria) this;
        }

        public Criteria andCrsNoIsNotNull() {
            addCriterion("CrsNo is not null");
            return (Criteria) this;
        }

        public Criteria andCrsNoEqualTo(String value) {
            addCriterion("CrsNo =", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoNotEqualTo(String value) {
            addCriterion("CrsNo <>", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoGreaterThan(String value) {
            addCriterion("CrsNo >", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoGreaterThanOrEqualTo(String value) {
            addCriterion("CrsNo >=", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoLessThan(String value) {
            addCriterion("CrsNo <", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoLessThanOrEqualTo(String value) {
            addCriterion("CrsNo <=", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoLike(String value) {
            addCriterion("CrsNo like", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoNotLike(String value) {
            addCriterion("CrsNo not like", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoIn(List<String> values) {
            addCriterion("CrsNo in", values, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoNotIn(List<String> values) {
            addCriterion("CrsNo not in", values, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoBetween(String value1, String value2) {
            addCriterion("CrsNo between", value1, value2, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoNotBetween(String value1, String value2) {
            addCriterion("CrsNo not between", value1, value2, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNameIsNull() {
            addCriterion("CrsName is null");
            return (Criteria) this;
        }

        public Criteria andCrsNameIsNotNull() {
            addCriterion("CrsName is not null");
            return (Criteria) this;
        }

        public Criteria andCrsNameEqualTo(String value) {
            addCriterion("CrsName =", value, "crsName");
            return (Criteria) this;
        }

        public Criteria andCrsNameNotEqualTo(String value) {
            addCriterion("CrsName <>", value, "crsName");
            return (Criteria) this;
        }

        public Criteria andCrsNameGreaterThan(String value) {
            addCriterion("CrsName >", value, "crsName");
            return (Criteria) this;
        }

        public Criteria andCrsNameGreaterThanOrEqualTo(String value) {
            addCriterion("CrsName >=", value, "crsName");
            return (Criteria) this;
        }

        public Criteria andCrsNameLessThan(String value) {
            addCriterion("CrsName <", value, "crsName");
            return (Criteria) this;
        }

        public Criteria andCrsNameLessThanOrEqualTo(String value) {
            addCriterion("CrsName <=", value, "crsName");
            return (Criteria) this;
        }

        public Criteria andCrsNameLike(String value) {
            addCriterion("CrsName like", value, "crsName");
            return (Criteria) this;
        }

        public Criteria andCrsNameNotLike(String value) {
            addCriterion("CrsName not like", value, "crsName");
            return (Criteria) this;
        }

        public Criteria andCrsNameIn(List<String> values) {
            addCriterion("CrsName in", values, "crsName");
            return (Criteria) this;
        }

        public Criteria andCrsNameNotIn(List<String> values) {
            addCriterion("CrsName not in", values, "crsName");
            return (Criteria) this;
        }

        public Criteria andCrsNameBetween(String value1, String value2) {
            addCriterion("CrsName between", value1, value2, "crsName");
            return (Criteria) this;
        }

        public Criteria andCrsNameNotBetween(String value1, String value2) {
            addCriterion("CrsName not between", value1, value2, "crsName");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table course
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}