package edu.hdu.classbox.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CrsApplyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    public CrsApplyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCrsNoIsNull() {
            addCriterion("CrsNo is null");
            return (Criteria) this;
        }

        public Criteria andCrsNoIsNotNull() {
            addCriterion("CrsNo is not null");
            return (Criteria) this;
        }

        public Criteria andCrsNoEqualTo(String value) {
            addCriterion("CrsNo =", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoNotEqualTo(String value) {
            addCriterion("CrsNo <>", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoGreaterThan(String value) {
            addCriterion("CrsNo >", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoGreaterThanOrEqualTo(String value) {
            addCriterion("CrsNo >=", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoLessThan(String value) {
            addCriterion("CrsNo <", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoLessThanOrEqualTo(String value) {
            addCriterion("CrsNo <=", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoLike(String value) {
            addCriterion("CrsNo like", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoNotLike(String value) {
            addCriterion("CrsNo not like", value, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoIn(List<String> values) {
            addCriterion("CrsNo in", values, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoNotIn(List<String> values) {
            addCriterion("CrsNo not in", values, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoBetween(String value1, String value2) {
            addCriterion("CrsNo between", value1, value2, "crsNo");
            return (Criteria) this;
        }

        public Criteria andCrsNoNotBetween(String value1, String value2) {
            addCriterion("CrsNo not between", value1, value2, "crsNo");
            return (Criteria) this;
        }

        public Criteria andStuNoIsNull() {
            addCriterion("UsrNo is null");
            return (Criteria) this;
        }

        public Criteria andStuNoIsNotNull() {
            addCriterion("UsrNo is not null");
            return (Criteria) this;
        }

        public Criteria andStuNoEqualTo(String value) {
            addCriterion("UsrNo =", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoNotEqualTo(String value) {
            addCriterion("UsrNo <>", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoGreaterThan(String value) {
            addCriterion("UsrNo >", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoGreaterThanOrEqualTo(String value) {
            addCriterion("UsrNo >=", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoLessThan(String value) {
            addCriterion("UsrNo <", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoLessThanOrEqualTo(String value) {
            addCriterion("UsrNo <=", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoLike(String value) {
            addCriterion("UsrNo like", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoNotLike(String value) {
            addCriterion("UsrNo not like", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoIn(List<String> values) {
            addCriterion("UsrNo in", values, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoNotIn(List<String> values) {
            addCriterion("UsrNo not in", values, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoBetween(String value1, String value2) {
            addCriterion("UsrNo between", value1, value2, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoNotBetween(String value1, String value2) {
            addCriterion("UsrNo not between", value1, value2, "stuNo");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCrsRoleIsNull() {
            addCriterion("CrsRole is null");
            return (Criteria) this;
        }

        public Criteria andCrsRoleIsNotNull() {
            addCriterion("CrsRole is not null");
            return (Criteria) this;
        }

        public Criteria andCrsRoleEqualTo(String value) {
            addCriterion("CrsRole =", value, "crsRole");
            return (Criteria) this;
        }

        public Criteria andCrsRoleNotEqualTo(String value) {
            addCriterion("CrsRole <>", value, "crsRole");
            return (Criteria) this;
        }

        public Criteria andCrsRoleGreaterThan(String value) {
            addCriterion("CrsRole >", value, "crsRole");
            return (Criteria) this;
        }

        public Criteria andCrsRoleGreaterThanOrEqualTo(String value) {
            addCriterion("CrsRole >=", value, "crsRole");
            return (Criteria) this;
        }

        public Criteria andCrsRoleLessThan(String value) {
            addCriterion("CrsRole <", value, "crsRole");
            return (Criteria) this;
        }

        public Criteria andCrsRoleLessThanOrEqualTo(String value) {
            addCriterion("CrsRole <=", value, "crsRole");
            return (Criteria) this;
        }

        public Criteria andCrsRoleLike(String value) {
            addCriterion("CrsRole like", value, "crsRole");
            return (Criteria) this;
        }

        public Criteria andCrsRoleNotLike(String value) {
            addCriterion("CrsRole not like", value, "crsRole");
            return (Criteria) this;
        }

        public Criteria andCrsRoleIn(List<String> values) {
            addCriterion("CrsRole in", values, "crsRole");
            return (Criteria) this;
        }

        public Criteria andCrsRoleNotIn(List<String> values) {
            addCriterion("CrsRole not in", values, "crsRole");
            return (Criteria) this;
        }

        public Criteria andCrsRoleBetween(String value1, String value2) {
            addCriterion("CrsRole between", value1, value2, "crsRole");
            return (Criteria) this;
        }

        public Criteria andCrsRoleNotBetween(String value1, String value2) {
            addCriterion("CrsRole not between", value1, value2, "crsRole");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("Status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("Status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("Status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("Status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("Status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("Status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("Status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("Status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("Status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("Status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("Status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("Status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("Status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("Status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rel_cs_usr
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rel_cs_usr
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}