package edu.hdu.classbox.bean;

import java.util.Date;

public class CrsApply extends CrsApplyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_cs_usr.CreateTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_cs_usr.CrsRole
     *
     * @mbggenerated
     */
    private String crsRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_cs_usr.Status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_cs_usr.CreateTime
     *
     * @return the value of rel_cs_usr.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_cs_usr.CreateTime
     *
     * @param createTime the value for rel_cs_usr.CreateTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_cs_usr.CrsRole
     *
     * @return the value of rel_cs_usr.CrsRole
     *
     * @mbggenerated
     */
    public String getCrsRole() {
        return crsRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_cs_usr.CrsRole
     *
     * @param crsRole the value for rel_cs_usr.CrsRole
     *
     * @mbggenerated
     */
    public void setCrsRole(String crsRole) {
        this.crsRole = crsRole == null ? null : crsRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_cs_usr.Status
     *
     * @return the value of rel_cs_usr.Status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_cs_usr.Status
     *
     * @param status the value for rel_cs_usr.Status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}