package edu.hdu.classbox.bean;

import java.util.ArrayList;
import java.util.List;

public class StudentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    public StudentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andStuNoIsNull() {
            addCriterion("StuNo is null");
            return (Criteria) this;
        }

        public Criteria andStuNoIsNotNull() {
            addCriterion("StuNo is not null");
            return (Criteria) this;
        }

        public Criteria andStuNoEqualTo(String value) {
            addCriterion("StuNo =", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoNotEqualTo(String value) {
            addCriterion("StuNo <>", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoGreaterThan(String value) {
            addCriterion("StuNo >", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoGreaterThanOrEqualTo(String value) {
            addCriterion("StuNo >=", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoLessThan(String value) {
            addCriterion("StuNo <", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoLessThanOrEqualTo(String value) {
            addCriterion("StuNo <=", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoLike(String value) {
            addCriterion("StuNo like", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoNotLike(String value) {
            addCriterion("StuNo not like", value, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoIn(List<String> values) {
            addCriterion("StuNo in", values, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoNotIn(List<String> values) {
            addCriterion("StuNo not in", values, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoBetween(String value1, String value2) {
            addCriterion("StuNo between", value1, value2, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNoNotBetween(String value1, String value2) {
            addCriterion("StuNo not between", value1, value2, "stuNo");
            return (Criteria) this;
        }

        public Criteria andStuNameIsNull() {
            addCriterion("StuName is null");
            return (Criteria) this;
        }

        public Criteria andStuNameIsNotNull() {
            addCriterion("StuName is not null");
            return (Criteria) this;
        }

        public Criteria andStuNameEqualTo(String value) {
            addCriterion("StuName =", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotEqualTo(String value) {
            addCriterion("StuName <>", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameGreaterThan(String value) {
            addCriterion("StuName >", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameGreaterThanOrEqualTo(String value) {
            addCriterion("StuName >=", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameLessThan(String value) {
            addCriterion("StuName <", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameLessThanOrEqualTo(String value) {
            addCriterion("StuName <=", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameLike(String value) {
            addCriterion("StuName like", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotLike(String value) {
            addCriterion("StuName not like", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameIn(List<String> values) {
            addCriterion("StuName in", values, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotIn(List<String> values) {
            addCriterion("StuName not in", values, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameBetween(String value1, String value2) {
            addCriterion("StuName between", value1, value2, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotBetween(String value1, String value2) {
            addCriterion("StuName not between", value1, value2, "stuName");
            return (Criteria) this;
        }

        public Criteria andAcadIdIsNull() {
            addCriterion("AcadId is null");
            return (Criteria) this;
        }

        public Criteria andAcadIdIsNotNull() {
            addCriterion("AcadId is not null");
            return (Criteria) this;
        }

        public Criteria andAcadIdEqualTo(Integer value) {
            addCriterion("AcadId =", value, "acadId");
            return (Criteria) this;
        }

        public Criteria andAcadIdNotEqualTo(Integer value) {
            addCriterion("AcadId <>", value, "acadId");
            return (Criteria) this;
        }

        public Criteria andAcadIdGreaterThan(Integer value) {
            addCriterion("AcadId >", value, "acadId");
            return (Criteria) this;
        }

        public Criteria andAcadIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("AcadId >=", value, "acadId");
            return (Criteria) this;
        }

        public Criteria andAcadIdLessThan(Integer value) {
            addCriterion("AcadId <", value, "acadId");
            return (Criteria) this;
        }

        public Criteria andAcadIdLessThanOrEqualTo(Integer value) {
            addCriterion("AcadId <=", value, "acadId");
            return (Criteria) this;
        }

        public Criteria andAcadIdIn(List<Integer> values) {
            addCriterion("AcadId in", values, "acadId");
            return (Criteria) this;
        }

        public Criteria andAcadIdNotIn(List<Integer> values) {
            addCriterion("AcadId not in", values, "acadId");
            return (Criteria) this;
        }

        public Criteria andAcadIdBetween(Integer value1, Integer value2) {
            addCriterion("AcadId between", value1, value2, "acadId");
            return (Criteria) this;
        }

        public Criteria andAcadIdNotBetween(Integer value1, Integer value2) {
            addCriterion("AcadId not between", value1, value2, "acadId");
            return (Criteria) this;
        }

        public Criteria andWeChatNoIsNull() {
            addCriterion("WeChatNo is null");
            return (Criteria) this;
        }

        public Criteria andWeChatNoIsNotNull() {
            addCriterion("WeChatNo is not null");
            return (Criteria) this;
        }

        public Criteria andWeChatNoEqualTo(String value) {
            addCriterion("WeChatNo =", value, "weChatNo");
            return (Criteria) this;
        }

        public Criteria andWeChatNoNotEqualTo(String value) {
            addCriterion("WeChatNo <>", value, "weChatNo");
            return (Criteria) this;
        }

        public Criteria andWeChatNoGreaterThan(String value) {
            addCriterion("WeChatNo >", value, "weChatNo");
            return (Criteria) this;
        }

        public Criteria andWeChatNoGreaterThanOrEqualTo(String value) {
            addCriterion("WeChatNo >=", value, "weChatNo");
            return (Criteria) this;
        }

        public Criteria andWeChatNoLessThan(String value) {
            addCriterion("WeChatNo <", value, "weChatNo");
            return (Criteria) this;
        }

        public Criteria andWeChatNoLessThanOrEqualTo(String value) {
            addCriterion("WeChatNo <=", value, "weChatNo");
            return (Criteria) this;
        }

        public Criteria andWeChatNoLike(String value) {
            addCriterion("WeChatNo like", value, "weChatNo");
            return (Criteria) this;
        }

        public Criteria andWeChatNoNotLike(String value) {
            addCriterion("WeChatNo not like", value, "weChatNo");
            return (Criteria) this;
        }

        public Criteria andWeChatNoIn(List<String> values) {
            addCriterion("WeChatNo in", values, "weChatNo");
            return (Criteria) this;
        }

        public Criteria andWeChatNoNotIn(List<String> values) {
            addCriterion("WeChatNo not in", values, "weChatNo");
            return (Criteria) this;
        }

        public Criteria andWeChatNoBetween(String value1, String value2) {
            addCriterion("WeChatNo between", value1, value2, "weChatNo");
            return (Criteria) this;
        }

        public Criteria andWeChatNoNotBetween(String value1, String value2) {
            addCriterion("WeChatNo not between", value1, value2, "weChatNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}