package edu.hdu.classbox.bean;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.StuNo
     *
     * @mbggenerated
     */
    private String stuNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.StuName
     *
     * @mbggenerated
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.AcadId
     *
     * @mbggenerated
     */
    private Integer acadId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.WeChatNo
     *
     * @mbggenerated
     */
    private String weChatNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.StuNo
     *
     * @return the value of student.StuNo
     *
     * @mbggenerated
     */
    public String getStuNo() {
        return stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.StuNo
     *
     * @param stuNo the value for student.StuNo
     *
     * @mbggenerated
     */
    public void setStuNo(String stuNo) {
        this.stuNo = stuNo == null ? null : stuNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.StuName
     *
     * @return the value of student.StuName
     *
     * @mbggenerated
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.StuName
     *
     * @param stuName the value for student.StuName
     *
     * @mbggenerated
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.AcadId
     *
     * @return the value of student.AcadId
     *
     * @mbggenerated
     */
    public Integer getAcadId() {
        return acadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.AcadId
     *
     * @param acadId the value for student.AcadId
     *
     * @mbggenerated
     */
    public void setAcadId(Integer acadId) {
        this.acadId = acadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.WeChatNo
     *
     * @return the value of student.WeChatNo
     *
     * @mbggenerated
     */
    public String getWeChatNo() {
        return weChatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.WeChatNo
     *
     * @param weChatNo the value for student.WeChatNo
     *
     * @mbggenerated
     */
    public void setWeChatNo(String weChatNo) {
        this.weChatNo = weChatNo == null ? null : weChatNo.trim();
    }
}