package edu.hdu.classbox.bean;

public class Team {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.TmNo
     *
     * @mbggenerated
     */
    private String tmNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.CrsNo
     *
     * @mbggenerated
     */
    private String crsno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.TmName
     *
     * @mbggenerated
     */
    private String tmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.TmPointAll
     *
     * @mbggenerated
     */
    private Float tmPointAll;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.TmNo
     *
     * @return the value of team.TmNo
     *
     * @mbggenerated
     */
    public String getTmNo() {
        return tmNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.TmNo
     *
     * @param tmNo the value for team.TmNo
     *
     * @mbggenerated
     */
    public void setTmNo(String tmNo) {
        this.tmNo = tmNo == null ? null : tmNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.CrsNo
     *
     * @return the value of team.CrsNo
     *
     * @mbggenerated
     */
    public String getCrsno() {
        return crsno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.CrsNo
     *
     * @param crsno the value for team.CrsNo
     *
     * @mbggenerated
     */
    public void setCrsno(String crsno) {
        this.crsno = crsno == null ? null : crsno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.TmName
     *
     * @return the value of team.TmName
     *
     * @mbggenerated
     */
    public String getTmName() {
        return tmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.TmName
     *
     * @param tmName the value for team.TmName
     *
     * @mbggenerated
     */
    public void setTmName(String tmName) {
        this.tmName = tmName == null ? null : tmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.TmPointAll
     *
     * @return the value of team.TmPointAll
     *
     * @mbggenerated
     */
    public Float getTmPointAll() {
        return tmPointAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.TmPointAll
     *
     * @param tmPointAll the value for team.TmPointAll
     *
     * @mbggenerated
     */
    public void setTmPointAll(Float tmPointAll) {
        this.tmPointAll = tmPointAll;
    }
}