package edu.hdu.classbox.bean;

public class TmApplyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_tm_usr.TmNo
     *
     * @mbggenerated
     */
    private String tmNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_tm_usr.UsrNo
     *
     * @mbggenerated
     */
    private String stuNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_tm_usr.TmNo
     *
     * @return the value of rel_tm_usr.TmNo
     *
     * @mbggenerated
     */
    public String getTmNo() {
        return tmNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_tm_usr.TmNo
     *
     * @param tmNo the value for rel_tm_usr.TmNo
     *
     * @mbggenerated
     */
    public void setTmNo(String tmNo) {
        this.tmNo = tmNo == null ? null : tmNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_tm_usr.UsrNo
     *
     * @return the value of rel_tm_usr.UsrNo
     *
     * @mbggenerated
     */
    public String getStuNo() {
        return stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_tm_usr.UsrNo
     *
     * @param stuNo the value for rel_tm_usr.UsrNo
     *
     * @mbggenerated
     */
    public void setStuNo(String stuNo) {
        this.stuNo = stuNo == null ? null : stuNo.trim();
    }
}