package edu.hdu.classbox.bean;

public class TmApply extends TmApplyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_tm_usr.TmRole
     *
     * @mbggenerated
     */
    private String tmRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rel_tm_usr.Status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_tm_usr.TmRole
     *
     * @return the value of rel_tm_usr.TmRole
     *
     * @mbggenerated
     */
    public String getTmRole() {
        return tmRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_tm_usr.TmRole
     *
     * @param tmRole the value for rel_tm_usr.TmRole
     *
     * @mbggenerated
     */
    public void setTmRole(String tmRole) {
        this.tmRole = tmRole == null ? null : tmRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rel_tm_usr.Status
     *
     * @return the value of rel_tm_usr.Status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rel_tm_usr.Status
     *
     * @param status the value for rel_tm_usr.Status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}